// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCADjc4QPyZ-byXklJyDrztiyZjUTFvS3g',
    appId: '1:453141234858:web:8b308e3bad75dee8fa3cd3',
    messagingSenderId: '453141234858',
    projectId: 'chat-app-e2f52',
    authDomain: 'chat-app-e2f52.firebaseapp.com',
    storageBucket: 'chat-app-e2f52.firebasestorage.app',
    measurementId: 'G-CPWTY50H68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN0otv-YoCpwB038ygE0dxM_yUND8BxB0',
    appId: '1:453141234858:android:a775385b8befd007fa3cd3',
    messagingSenderId: '453141234858',
    projectId: 'chat-app-e2f52',
    storageBucket: 'chat-app-e2f52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BDyTJ2-BGJfAnO-liJXc7a2jb1-qsrI',
    appId: '1:453141234858:ios:0892caa8ac5aee21fa3cd3',
    messagingSenderId: '453141234858',
    projectId: 'chat-app-e2f52',
    storageBucket: 'chat-app-e2f52.firebasestorage.app',
    iosBundleId: 'com.example.chatApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9BDyTJ2-BGJfAnO-liJXc7a2jb1-qsrI',
    appId: '1:453141234858:ios:0892caa8ac5aee21fa3cd3',
    messagingSenderId: '453141234858',
    projectId: 'chat-app-e2f52',
    storageBucket: 'chat-app-e2f52.firebasestorage.app',
    iosBundleId: 'com.example.chatApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCADjc4QPyZ-byXklJyDrztiyZjUTFvS3g',
    appId: '1:453141234858:web:71dbfbc0674cf38bfa3cd3',
    messagingSenderId: '453141234858',
    projectId: 'chat-app-e2f52',
    authDomain: 'chat-app-e2f52.firebaseapp.com',
    storageBucket: 'chat-app-e2f52.firebasestorage.app',
    measurementId: 'G-XF7B66DE94',
  );
}
